import { plainInt, plainOne, plainTwo } from "./format";
import type { CalculatorInputs, CalculatorResult } from "./model";

export interface ContactDetails {
  email: string;
  phone: string;
  topics: string[];
}

/** The plain-text body that goes into the user's mail client. */
export const buildQuotationSummary = (
  inputs: CalculatorInputs,
  result: CalculatorResult,
  contact: ContactDetails,
): string => {
  const lines: string[] = [
    "REQUEST FOR QUOTATION - FuelEU compliance units",
    "",
    "Please send me a price for the units below.",
    "",
  ];

  if (contact.email) lines.push(`Email: ${contact.email}`);
  if (contact.phone) lines.push(`Phone: ${contact.phone}`);
  if (contact.topics.length) {
    lines.push("", `Please help me with: ${contact.topics.join(", ")}.`);
  }

  lines.push(
    "",
    "--- Calculation ---",
    `Fossil fuel replaced: ${result.fuel.name} (${plainTwo(result.fuel.ci)} gCO2e/MJ)`,
    `Tonnes replaced: ${plainInt(result.tons)} t`,
    `Biofuel GHG intensity: ${plainOne(inputs.ciBio)} gCO2e/MJ`,
    `Compliance surplus generated: ${plainInt(result.surplus)} tCO2e (assuming all energy in scope)`,
    "",
    `Fossil fuel price: ${plainInt(inputs.priceFossil)} USD/t`,
    `Biofuel price: ${plainInt(inputs.priceBio)} USD/t`,
    `Biofuel premium: ${plainInt(result.premium)} USD`,
    `FuelEU penalty avoided: ${plainInt(result.penaltyAvoided)} USD (${plainInt(result.penaltyRate)} USD per tCO2e)`,
    `ETS cost avoided: ${plainInt(result.ets)} USD (EUA ${plainTwo(inputs.eua)} EUR, EURUSD ${plainTwo(result.fx)})`,
    `Value created: ${plainInt(result.value)} USD`,
    `Net result: ${plainInt(result.net)} USD`,
    "",
    `Generated by the Ahti Climate surplus calculator on ${new Date().toISOString().slice(0, 10)}.`,
  );

  return lines.join("\n");
};
