import { plainInt, plainOne, plainTwo } from "./format";
import type { CalculatorInputs, CalculatorResult } from "./model";

export interface ContactDetails {
  email: string;
  phone: string;
  topics: string[];
}

/** The plain-text body that goes into the user's mail client. */
export const buildQuotationSummary = (
  inputs: CalculatorInputs,
  result: CalculatorResult,
  contact: ContactDetails,
): string => {
  const lines: string[] = [
    "REQUEST FOR QUOTATION - FuelEU compliance units",
    "",
    "Please send me a price for the units below.",
    "",
  ];

  if (contact.email) lines.push(`Email: ${contact.email}`);
  if (contact.phone) lines.push(`Phone: ${contact.phone}`);
  if (contact.topics.length) {
    lines.push("", `Please help me with: ${contact.topics.join(", ")}.`);
  }

  lines.push(
    "",
    "--- Calculation ---",
    `Fossil fuel replaced: ${result.fuel.name} (${plainTwo(result.fuel.ci)} gCO2e/MJ)`,
    `Tonnes replaced: ${plainInt(result.tons)} t`,
    `Biofuel GHG intensity: ${plainOne(inputs.ciBio)} gCO2e/MJ`,
    `Compliance surplus generated: ${plainInt(result.surplus)} tCO2e (assuming all energy in scope)`,
    "",
    `Fossil fuel price: ${plainInt(inputs.priceFossil)} USD/t`,
    `Biofuel price: ${plainInt(inputs.priceBio)} USD/t`,
    `Biofuel premium: ${plainInt(result.premium)} USD`,
    `ETS cost avoided: ${plainInt(result.ets)} USD (EUA ${plainTwo(inputs.eua)} EUR, EURUSD ${plainTwo(result.fx)}) - earned either way`,
    "",
    "--- The surplus, one route or the other ---",
    `A) FuelEU penalty avoided: ${plainInt(result.penaltyAvoided)} USD (${plainInt(result.penaltyRate)} USD per tCO2e)`,
    `   Net result: ${plainInt(result.offsetNet)} USD`,
    `B) Profit from pooling: ${plainInt(result.poolProfit)} USD (${plainInt(inputs.poolPriceEur)} EUR per tCO2e)`,
    `   Net result: ${plainInt(result.poolNet)} USD`,
    "",
    `Generated by the Ahti Climate surplus calculator on ${new Date().toISOString().slice(0, 10)}.`,
  );

  return lines.join("\n");
};

/** The biofuel-supply enquiry, a separate ask from the units quotation. */
export const buildBiofuelOfferSummary = (
  inputs: CalculatorInputs,
  result: CalculatorResult,
  contact: ContactDetails,
  imo: string,
): string => {
  const lines: string[] = [
    "REQUEST FOR OFFER - marine biofuel",
    "",
    "Please send me an offer for the volume below.",
    "",
  ];

  if (contact.email) lines.push(`Email: ${contact.email}`);
  if (contact.phone) lines.push(`Phone: ${contact.phone}`);
  if (imo) lines.push(`Vessel IMO: ${imo}`);

  lines.push(
    "",
    "--- Requirement ---",
    `Volume: ${plainInt(inputs.tons)} t, replacing ${result.fuel.name} tonne for tonne`,
    `Target GHG intensity: ${plainOne(inputs.ciBio)} gCO2e/MJ well-to-wake, certified`,
    `Price assumed in my calculation: ${plainInt(inputs.priceBio)} USD/t delivered`,
    `Fossil price assumed: ${plainInt(inputs.priceFossil)} USD/t`,
    `Compliance surplus this generates: ${plainInt(result.surplus)} tCO2e`,
    "",
    `Generated by the Ahti Climate surplus calculator on ${new Date().toISOString().slice(0, 10)}.`,
  );

  return lines.join("\n");
};
